class MentorLocators:
    HOME = "//div[text()='Home']"
    CUSTOMISE_WEEKLY_SCHEDULE = "//button[text()='Customise Weekly Schedule']"
    ADD_SLOT_BUTTON = "(//div[@class='actions']//button)[1]"
    START_TIME_SLOT = "(//div[@class='interval_container_inner']//div[@class='ant-select-selector'])[1]"
    START_TIME_OPTION = "//span[text()='12:00 AM']"
    END_TIME_SLOT = "(//div[@class='interval_container_inner']//div[@class='ant-select-selector'])[2]"
    END_TIME_SLOT_OPTION = "//span[text()='12:30 AM']"
    COPY_SLOT_BUTTON = "(//button[@class='ant-btn icon-button action_button false'])[1]"
    SLOT_COPY_APPLY_BUTTON = "//button[text()='Apply']"
    CLOSE_SLOT_BUTTON = "(//button[@class='ant-btn ant-btn-default icon-button close_action_button'])[1]"
    ADD_OVERRIDE_BUTTON = "//button[text()='Add an Override']"
    FIRST_DATE_OVERRIDE = "//div[contains(@style,'cursor: pointer')][1]"
    SAVE_DATE_OVERRIDE_BUTTON = "(//button[text()='Save'])[2]"
    DELETE_ICON = "//div[@class='delete_icon_wrapper']"
    SAVE_BUTTON = "(//button[text()='Save'])[1]"