class BatchDetailsCollaboratesetupLocators:
    FIRST_BATCH_CARD = "(//td[@class='ant-table-cell batch-list-content-bold'])[1]"
    BATCH_NAME = "//div[@class='batch-name-div']"
    COLLABORATESETUP_TAB="//p[contains(text(), 'Collaborate Setup')]"
    COLLABORATE_TITLE ="//h4[contains(text(), 'Customise collaborate activity')]"
    COLLABORATE_EDIT_BUTTON="(//button[normalize-space()='Edit'])[1]"
    LEVEL1_SECTION="(//div[@class='radio_option false'])[1]"
    LEVEL2_SECTION="(//div[@class='radio_option false'])[2]"
    COLLABORATE_SAVE_BUTTON="(//button[normalize-space()='Save'])[1]"
    SELECTED_CAREER_PLANS_SECTION="(//div[@class='career-plans-container'])[1]"