class CreateNewBatchLocators:
    CREATE_NEWBATCH_BUTTON="//button[contains(text(),'Create New Batch')]"
    BATCH_INFORMATION_HEADER_SECTION="//div[@class='createBatch_stepper_container']"
    BATCH_INFORMATION_TITLE="//div[contains(text(),'Batch Information')]"
    Institute_DROPDOWN="//label[contains(text(),'Institute')]/following-sibling::div"
    Institute_DROPDOWN_OPTION="//span[contains(text(),'INS_JULY1_QA')]"
    FACULTY_PRESELECTED_NAME="//span[contains(text(),'Leela fac')]"
    SELECT_COURSE_DROPDOWN="//span[contains(text(),'select course')]"
    SELECT_COURSE_DROPDOWN_OPTION="//span[contains(text(),' QA-Emp skill Test-V2')]"
    BATCH_NAME_INPUT="//input[@placeholder='provide batch name']"
    BATCH_START_END_DATE="//div[@id='create-batch-startedAt']"
    BATCH_DATEPICKER_INPUT="//div[@class='ant-picker-input']"
    DATE_PICKER_HEADER="//div[@class='ant-picker-header']"
    DATE_PICKER_BODY="//div[@class='ant-picker-body']"
    DATE_PICKER_TODAY_TEXT="//div[@class='ant-picker-today-btn']"
    NEXT_YEAR_BUTTON="//button[@class='ant-picker-header-super-next-btn']"
    BATCH_ENDDATE="(//div[normalize-space()='23'])[1]"
    NEXT_MONTH_BUTTON="//button[@class='ant-picker-header-next-btn']"
    STUDENT_ENROLLMENT_NOTE="//div[@class='student-erollment-note']"
    WEEKELY_CLASS_HOURS="//input[@id='weekly-hours']"
    CONFIRM_CHECKBOX="//span[@class='ant-checkbox-inner']"
    MAX_STUDENTS_ALLOWED_INPUT="//input[@name='maxStudentsAllowed']"
    NEXT_BUTTON="(//button[normalize-space()='Next'])[1]"
    CONFIRM_DATES_POPUP="(//div[@class='ant-modal-body'])"
    CONFIRM_AND_PROCEED_BUTTON="//button[normalize-space()='Confirm & Proceed']"
    ASSESSMENT_DETAILS_SECTION="//div[@class='assessment_details_wrapper']"
    ASSESSMENT_DETAILS_NEXT_BUTTON="(//button[normalize-space()='Next'])[1]"
    DIFFICULY_LEVEL1_CARD="(//div[@class='radio_option false'])[1]"
    DIFFICULY_LEVEL2_CARD="(//div[@class='radio_option false'])[2]"
    DIFFICULY_LEVEL3_CARD="(//div[@class='radio_option false'])[3]"
    LEVEL1_RADIO_BUTTON="(//input[@value='Basic'])[1]"
    LEVEL2_RADIO_BUTTON="(//input[@value='Intermediate'])[1]"
    LEVEL3_RADIO_BUTTON="(//input[@value='Advanced'])[1]"
    JOBEROLE_OR_SECTOR_INPUT="//input[@placeholder='Type one job role or sector and press enter']"
    JOBEROLE_OR_SECTOR_ENTER_BUTTON="//button[contains(text(),'Enter')]"
    SAVE_AND_FINISH_BUTTON="//button[contains(text(),'Save & Finish')]"
    BATCH_DETAILS_CARD="(//div[@class='section_card_container card'])[1]"


