class careerbuddy_locators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    CAREER_BUDDY_CARD = "(//button[@class='new-student-dashboard__card'])[7]"
    SEARCH_MENTORS_INPUT = "//input[@placeholder='Search Mentors']"
    RECOMMENDED_MENTOR_CARD = "(//span[@class='ant-avatar-string'])[2]"
    VALIDATE_SECTORS_HEADER = "(//p[text()='Sectors'])[1]"
    VALIDATE_JOB_ROLES_HEADER = "(//p[text()='Job Roles'])[1]"
    VALIDATE_LANGUAGE_HEADER = "(//p[text()='Language'])[1]"
    LANGUAGE_BUTTON = "//button[text()='Language  ']"
    LANGUAGE_OPTION_ENGLISH = "//p[text()='English']"
    APPLY_BUTTON = "//button[text()='Apply']"
    LANGUAGE_CLOSE_BUTTON = "(//*[name()='svg'])[1]"
    SECTOR_BUTTON = "//button[text()='Sector  ']"
    SECTOR_OPTION_HEALTHCARE = "//p[text()='Healthcare']"
    APPLY_BUTTON = "//button[text()='Apply']"
    SECTOR_CLOSE_BUTTON = "(//*[name()='svg'])[2]"
    LOCATION_BUTTON = "//button[text()='Location  ']"
    LOCATION_OPTION_BANGALORE = "//p[text()='Bangalore, India']"
    APPLY_BUTTON = "//button[text()='Apply']"
    LOCATION_CLOSE_BUTTON = "(//*[name()='svg'])[3]"
    JOBROLE_BUTTON = "//button[text()='Job Role  ']"
    JOBROLE_OPTION_SALES_ASSOCIATE = "//p[text()='Sales Associate']"
    APPLY_BUTTON = "//button[text()='Apply']"
    JOB_ROLE_CLOSE_BUTTON = "(//*[name()='svg'])[4]"
    BOOK_SESSION_BUTTON = "//button[text()='Book Session']"
    AVAILABLE_SELECT_DATE = "//div[contains(@style,'cursor: pointer')]"
    SLOT_BUTTON = "//button[@class='ant-btn ant-btn-default slot']"
    SESSION_PURPOSE_LABEL = "//label[text()='What is the purpose of this session for you?*']"
    SESSION_PURPOSE_DROPDOWN = "//div[contains(@class,'ant-select-dropdown')]"
    JOB_SEARCH_STRATEGY_OPTION = "//div[contains(@class,'ant-select-item-option-content') and contains(.,'Job Search Strategy')]"
    SPECIFIC_OUTCOME_LABEL = "//label[text()='What specific outcome do you want from this session?*']"
    SPECIFIC_OUTCOME_TEXTAREA = "//textarea"
    CHECKBOX_OPTION = "//span[@class='ant-checkbox-inner']"
    BOOK_BUTTON = "//button[text()='Book']"
    COPY_LINK_OPTION = "//span[text()='Copy Link']"

