class coursesLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    COURSES_CARD = "//h6[text()='Courses']"
    VALIDATE_INPROGRESS_TAB= "//h5[contains(text(), 'In Progress')]"
    VALIDATE_COMPLETED_TAB= "//h5[contains(text(), 'Completed')]"
    ENROLLED_COURSE_CARD = "(//div[@class='new-enrolled-course-card'])[1]"
    VIEW_DETAILS_BUTTON = "(//button[text()='View Details'])[1]"
    OVERVIEW = "//p[text()='Overview']"
    COURSE_CONTENT = "//p[text()='Course Content']"
    PERFORMANCE = "//p[text()='Performance']"
    VALIDATE_FINAL_SCORE = "//div[@class='ant-col ant-col-md-7 score_container']"
    VALIDATE_CERTIFICATE = "//div[@class='firstScenario_container']"
    VALIDATE_PERFORMANCE = "//div[@class='assessmentBasedScenario_container']"
    #for prod environment the below locators till pitch trainer back arrow button will not work so these locators will be executed only in dev environment
    VIEW_ANALYSIS_BUTTON = "//button[text()='View Analysis']"
    VIEW_PITCH_BUTTON = "//p[text()='View Pitch']"
    VIDEO_PLAY_BUTTON = "//video[text()='Your browser does not support the video tag.']"
    VIDEO_CLOSE_BUTTON = "//span[@class='ant-modal-close-x']"
    SHARE_PITCH_BUTTON = "//button[@class='ant-btn ant-btn-default secondary_button view-pitch-button default-share-button share-pitch-button']"
    COPY_SHARE_BUTTON = "//img[@class='wf_image  no-js-share-button-copy']"
    SHARE_PITCH_CLOSE_BUTTON = "//span[@class='ant-modal-close-x']"
    BACK_ARROW_BUTTON = "//img[@class='wf_image redirection-image no-js-pitch-trainer-back-arrow']"
    CREATE_POST_VIDEO_BUTTON = "//button[text()='Create Post-Video']"
    PITCH_TRAINER_BACK_ARROW_BUTTON = "//img[@class='wf_image back-btn false no-js-ArrowLeftDark']"
    COURSES_RECOMMENDED_BY_INSTITUTE = "//h6[text()='Courses Recommended by Your Institute']"
    VALIDATE_RECOMMENDED_COURSE_CARD = "(//div[@class='new-recommended-course-card'])[1]"
    COURSES_OFFERED_BY_WADHWANI_FOUNDATION = "//h6[text()='Courses offered by wadhwani foundation']"
    VALIDATE_OFFERED_COURSE_CARD = "(//div[@class='new-recommended-course-card'])[13]"
    