class interviewCoachLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    INTERVIEW_COACH_CARD = "(//button[@class='new-student-dashboard__card'])[4]"
    AUDIO_BUTTON_IMAGE = "//img[@class='audio-button-image']"
    VALIDATE_MIC_BUTTON = "//img[contains(@class,'mic-on-image')]"
    INTERVIEW_SEARCH_INPUT = "//input[@placeholder='For eg, Retail Sales Associate, Electronics']"
    INTERVIEW_COACH_SEND_ICON = "//img[@alt='interviewCoachSendIcon']"
    PRACTISE_INTERVIEW_BUTTON = "//button[text()='Practise Interviewing for the role']"
    START_BUTTON = "//button[contains(text(),'Start')]"
    PITCH_TRAINER_BACK_ICON = "//img[@alt='pitchTrainerBackIcon']"
    VALIDATE_YOUR_RECENT_ROLES_HEADER = "//h1[text()='Your Recent Roles']"
    VALIDATE_ONGOING_HEADER = "//h1[text()='Ongoing']"
    VALIDATE_COMPLETED_HEADER = "//h1[text()='Completed']"
    THREEDOTS_MORE_DETAILS_ICON = "//img[@alt='moreDetails']"
    DELETE_ROLE_BUTTON = "//p[text()='Delete this role']"
    DELETE_ROLE_CONFIRM_BUTTON = "//button[text()='Confirm']"
