class jobsconnectLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    JOBS_CONNECT_CARD = "//h6[text()='Jobs Connect']"
    VALIDATE_JOBS_CONNECT_HEADER = "//h4[text()='Jobs Connect']"
    VALIDATE_ALL_FILTERS = "//div[text()='All Filters']"
    JOB_TYPE_FILTER = "//div[text()='Job Type']/parent::div/parent::div"
    FULL_TIME_OPTION = "//a[text()='Full time']"
    WORK_MODE_FILTER = "//div[text()='Work Mode']/parent::div/parent::div"
    OFFICE_OPTION = "//a[text()='Office']"
    INDUSTRY_SECTOR_FILTER = "//div[text()='Industry/Sector']/parent::div/parent::div"
    AUTOMOTIVE_OPTION = "//a[text()='Automotive']"
    EDUCATION_LEVEL_FILTER = "//div[text()='Education Level']/parent::div/parent::div"
    GRADUATE_OPTION = "//span[text()='Graduate']"
    PREFERRED_COMPANIES_FILTER = "//div[text()='Preferred Companies']/parent::div/parent::div"
    JOB_OPTION = "//div[text()='Test_Full Job Creation']"
    #for prod environment consider below locator
    JOB_OPTION = "//div[text()='Backoffice &amp; Voice Executive']"
    JOBS_LINK = "//a[text()='Jobs']"
    SEARCH_BY_JOB_TITLE = "//input[@placeholder='Search by job title/roles']"
    FIND_JOBS_BUTTON = "//button[text()='Find Jobs']"
    FIRST_JOB_CARD = "(//div[@class='job-card-upper-wrapper'])[1]"
    VALIDATE_ABOUT_THE_JOB_BUTTON = "//button[text()='About the job']"
    VALIDATE_ABOUT_THE_COMPANY_BUTTON = "//button[text()='About the company']"
    VALIDATE_APPLY_BUTTON = "(//button[text()='Apply'])[1]"
    RESET_BUTTON = "(//button[text()='Reset'])[1]"
    JOBS_CONNECT_APPLIED_STATUS = "//p[contains(text(), 'Applied')]"
    APPLIED_JOBS_BUTTON = "//button[text()='Applied Jobs']"
    APPLIED_JOB_CARD = "(//div[contains(@class,'job-card-upper-wrapper')])[1]"
    