class mycareeradvisorLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    MY_CAREER_ADVISOR = "(//button[@class='new-student-dashboard__card'])[6]"
    PASSIONS_HEADER = "//h4[text()='Passions']"
    PASSION_REVIEW_BUTTON = "//button[text()='Review']"
    PASSION_SELECTED_ITEMS = "//div[@class='selected-items']"
    ARTS_AND_DESIGN = "//*[contains(text(),'Arts & Design')]"
    DRAWING_AND_ILLUSTRATION_CHECKBOX = "//input[@id='drawingAndIllustration']"
    SUBMIT_BUTTON = "//button[text()='Submit']"
    QUESTIONNAIRES_HEADER = "//h4[text()='Questionnaires']"
    APTITUDE_REVIEW_BUTTON = "(//button[text()='Review'])[1]"
    REATTEMPT_BUTTON = "//button[text()='Reattempt']"
    SLIDER_CHOOSE_BUTTON = "(//button[text()='Choose'])[2]"
    SLIDER_QUESTION_SEQUENCE= "//p[@class='para1 regular slider-sequence' and contains(text(),'1')]"
    SLIDER_HANDLE = "//div[@class='questionnaire-slider-container'][1]//div[contains(@class,'ant-slider-handle')]"
    SLIDER_SEQUENCE_9 = "//div[@class='questionnaire-slider-container'][1]//span[text()='9']"
    SLIDER_SEQUENCE_10 = "//div[@class='questionnaire-slider-container'][1]//span[text()='10']"
    UPDATE_BUTTON = "//button[text()='Update']"
    GO_TO_MATCHED_ROLES_BUTTON = "//button[text()='Go to Matched Roles']"
    WITHOUT_COLLEGE_DEGREE = "//span[text()='Without College Degree']"
    VALIDATE_HEADER_COUNT = "//span[@class='header-count']"
    SEARCH_ROLES_HEADER = "//h4[text()='Search Roles']"
    SEARCH_FOR_JOB_ROLE_INPUT = "//input[@placeholder='Search for a Job Role']"
    RESULTS_HEADER = "//h4[text()='Results']/following::h4[1]"
    ADD_FAVOURITE = "//h4[text()='Favourite']"
    FAVOURITES_HEADER = "//h4[text()='Favourites']"
    SHARE_REPORT = "(//h4[text()='Share Report'])[1]"
    SHARE_BUTTON = "//button[text()='Share']"
    REMOVE_FAVOURITE = "//h4[text()='Favourite']"
    