class NewHomepageLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    COURSES_CARD = "//h6[text()='Courses']"
    PROGRAMS_CARD = "//h6[text()='Programs']"
    PERSONAL_PITCH_TRAINER = "//h6[text()='Personal Pitch Trainer']"
    INTERVIEW_COACH = "//h6[text()='Interview Coach']"
    FORUMS_CARD = "//h6[text()='Forums']"
    MY_CAREER_ADVISOR_CARD = "//h6[text()='My Career Advisor']"
    CARRER_BUDDY_CARD = "//h6[text()='Career Buddy']"
    JOBS_CONNECT_CARD = "//h6[text()='Jobs Connect']"
    MENU_HELP_ICON = "//img[@class='wf_image  no-js-MenuHelp']"
    NOTIFICATION_ICON = "//img[@class='notification_icon']"
    PROFILE_ICON = "//span[@class='ant-avatar-string']"
    HEADER_PROFILE_MENU_ICON = "//img[@class='wf_image header_profile_menu_trigger__icon no-js-svg%3e']"
    CALENDAR = "//p[text()='Calendar']"
    MESSAGES_AND_DISCUSSIONS = "//p[text()='Messages & Discussions']"
    LEARNING_PROGRESS = "//p[text()='Learning Progress']"
    SETTINGS = "//p[text()='Settings']"
    LOG_OUT = "//p[text()='Logout']"

