class NewHomepageLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    COURSES_CARD = "(//button[@class='new-student-dashboard__card'])[1]"
    PROGRAMS_CARD = "(//button[@class='new-student-dashboard__card'])[2]"
    PERSONAL_PITCH_TRAINER = "(//button[@class='new-student-dashboard__card'])[3]"
    INTERVIEW_COACH = "(//button[@class='new-student-dashboard__card'])[4]"
    FORUMS_CARD = "(//button[@class='new-student-dashboard__card'])[5]"
    MY_CAREER_ADVISOR_CARD = "(//button[@class='new-student-dashboard__card'])[6]"
    CARRER_BUDDY_CARD = "(//button[@class='new-student-dashboard__card'])[7]"
    JOBS_CONNECT_CARD = "(//button[@class='new-student-dashboard__card'])[8]"
    MENU_HELP_ICON = "//img[@class='wf_image  no-js-MenuHelp']"
    NOTIFICATION_ICON = "//img[@class='notification_icon']"
    PROFILE_ICON = "//span[@class='ant-avatar-string']"
    HEADER_PROFILE_MENU_ICON = "//img[@class='wf_image header_profile_menu_trigger__icon no-js-svg%3e']"
    CALENDAR = "//p[text()='Calendar']"
    MESSAGES_AND_DISCUSSIONS = "//p[text()='Messages & Discussions']"
    LEARNING_PROGRESS = "//p[text()='Learning Progress']"
    SETTINGS = "//p[text()='Settings']"
    LOG_OUT = "//p[text()='Logout']"

