class personal_pitch_trainerLocators:
    HOME = "//div[text()='Home']"
    VALIDATE_WELCOME_HEADER = "//h1[text()='Welcome to']"
    VALIDATE_WADHWANI_SKILLING_HEADER = "//h1[text()='Wadhwani Skilling']"
    VALIDATE_EXPLORE_THINGS_TO_DO_HEADER = "//h4[text()='Explore things to do']"
    PERSONAL_PITCH_TRAINER = "(//button[@class='new-student-dashboard__card'])[3]"
    CREATE_YOUR_PITCH_BUTTON = "//button[text()='Create Your Pitch']"
    PITCH_TRAINER_BACK_ARROW_BUTTON = "//img[@class='wf_image redirection-image no-js-pitch-trainer-back-arrow']"
    PITCH_SUMMARY_VIEW_BUTTON = "//p[text()='View']"
    VIEW_PITCH_BUTTON = "//p[text()='View Pitch']"
    VIDEO_PLAY_BUTTON = "//video[text()='Your browser does not support the video tag.']"
    VIDEO_CLOSE_BUTTON = "//span[@class='ant-modal-close-x']"
    SHARE_PITCH_BUTTON = "//button[@class='ant-btn ant-btn-default secondary_button view-pitch-button default-share-button share-pitch-button']"
    COPY_SHARE_BUTTON = "//img[@class='wf_image  no-js-share-button-copy']"
    SHARE_PITCH_CLOSE_BUTTON = "//span[@class='ant-modal-close-x']"