class Learning_Progress_Locators:
    PROFILE_ICON="//div[@class='header_menu_container']//span[text()='VS']"
    LEARNING_PROGRESS="//h1[text()='Learning Progress']"
    VALIDATE_LEARNING_PROGRESS="//h6[text()='Learning Progress']"
    MY_COURSES="//h4[text()='My Courses']"
    ONGOING_COURSES="//P[contains(text(),'Ongoing')]"
    FIRST_ONGOING_COURSE="(//div[@class='course_card_container'])[position()=1]"
    VALIDATE_LEARNING_PROGRESSFIRST_ONGOING_COURSE_HEADING="//h1[@class='typography-text page-title heading-text']"  
    FIRST_ONGOING_COURSE_OVERVIEW="//p[text()='Overview']"
    FIRST_ONGOING_COURSE_CONTENT="//p[text()='Course Content']"
    FIRST_ONGOING_COURSE_PERFORMANCE="//p[text()='Performance']"
    COMPLETED_COURSES="//P[contains(text(),'Completed')]"
    FIRST_COMPLETED_COURSE="//div[@class='course_card_container']//div[text()='Completed'][1]"
    VALIDATE_LEARNING_PROGRESSFIRST_COMPLETED_COURSE_HEADING="//h1[@class='typography-text page-title heading-text']"
    FIRST_COMPLETED_COURSE_OVERVIEW="//p[text()='Overview']"
    FIRST_COMPLETED_COURSE_CONTENT="//p[text()='Course Content']"
    FIRST_COMPLETED_COURSE_PERFORMANCE="//p[text()='Performance']"
    VALIDATE_SCORE_VALUE="//div[@class='score_info']//span[@class='score_value']"
    VALIDATE_OVERALL_PROGRESS="//span[text()='Overall Progress']"
