
class LoginLocators:
<<<<<<< Updated upstream
    GET_STARTED_BUTTON = "//button[text()='Get Started']"
    LOGIN_BUTTON = "//p[text()='Continue with Email']"
    USERNAME_INPUT="//input[@placeholder='Enter your Email ID']"
    NEXT_BUTTON="//button[text()='Next']"
    PASSWORD_INPUT="//input[@type='password']"
    SUBMIT_BUTTON="//button[text()='Submit']"
    WADHWANI_LOGO="//img[@alt='wadhwani logo white color']"
    HOME_BUTTON="//div[@id='Home']"
    LOGIN_PAGE_HEADER="//h2[contains(text(),'Offered by')]"
    CARD="//div[contains(@class,'program_card__container')]"
    PARAGRAPH_NEW="//p[text()='EN program New']"
    CARRER_ADVISOR="//div[text()='Career Advisor']"
    GOT_IT_BUTTON="//span[text()='Got It']"
    PLACEMENT_PREP="//div[@id='Placement']"
    JOBS_CONNECT="//div[@id='Jobs']"
    CALENDER="(//div[contains(@class,'chat_container')]//img)[1]"
    SUPPORT_ICON="(//div[contains(@class,'chat_container')]//img)[2]"
    CHAT_ICON="(//div[contains(@class,'chat_container')]//img)[3]"
    NOTIFICATIONS_ICON="(//div[contains(@class,'chat_container')]//img)[4]"
    CLOSE_NOTIFICATION="//img[contains(@class,'notification__title__cross')]"
    PROFILE_ICON="//div[@class='header_menu_container']//span[text()='VS']"
    MY_PROFILE="//h1[text()='My Profile']"
    EDIT_BUTTON="//button[@class='ant-btn ant-btn-default edit-button']"
    FIRST_NAME="//input[@id='first-name']"
    LANGUAGE="//div[@id='language']"
    HINDI_LANGUAGE="//div[text()='Hindi']"
    ENGLISH_LANGUAGE="//div[text()='अंग्रेजी']"
    LAST_NAME="//input[@id='last-name']"
    SELECT_COUNTRY="//span[text()='India']"
    SELECT_CITY="//label[text()='Select City']//following::span[1]"
    SELECT_CITY_HINDI="//label[text()='शहर चुनें']/following::span[1]"
    SELECT_CITY_HYDERABAD="//p[text()='Hyderabad, Telangana, India']"
    SELECT_CITY_BANGALORE="//p[text()='Bangalore']"
    WHATSAPP_NUMBER="//input[@id='mobile-number']"
    VERIFY_WHATSAPP_NUMBER="//p[text()='Verify']"
    UPDATE_BUTTON="//button[@class='ant-btn ant-btn-default update-button']"
    PROFILE_INFORMATION_HINDI="//h4[text()='प्रोफ़ाइल जानकारी']"
    LOGOUT_BUTTON="//h1[normalize-space()='Logout']"
=======
    GET_STARTED_BUTTON = "//button[contains(@class,'guest-started-button')]"
    LOGIN_BUTTON = "//p[text()='Continue with Email']"
    USERNAME = "//input[@name='email']"
    NEXT_BUTTON = "//button//span[text()='Next']"
    PASSWORD = "//input[@placeholder='Enter password']"
    SUBMIT_BUTTON = "//button//span[text()='Submit']"
    WADHWANI_LOGO = "//img[@alt='wadhwani logo white color']"
    HOME_BUTTON = "//div[@id='Home']"
    LOGIN_PAGE_HEADER = "//h2[contains(text(),'Offered by')]"
    CARD = "//div[contains(@class,'program_card__container')]"
    PARAGRAPH_NEW = "//p[text()='EN program New']"
    CARRER_ADVISOR = "//div[text()='Career Advisor']"
    GOT_IT_BUTTON = "//span[text()='Got It']"
    PLACEMENT_PREP = "//div[@id='Placement']"
    JOBS_CONNECT = "//div[@id='Jobs']"
    CALENDER = "(//div[contains(@class,'chat_container')]//img)[1]"
    SUPPORT_ICON = "(//div[contains(@class,'chat_container')]//img)[2]"
    CHAT_ICON = "(//div[contains(@class,'chat_container')]//img)[3]"
    NOTIFICATIONS_ICON = "(//div[contains(@class,'chat_container')]//img)[4]"
    CLOSE_NOTIFICATION = "//img[contains(@class,'notification__title__cross')]"
    PROFILE_ICON = "(//div[@class='ant-dropdown-trigger profile_container_wrapper'])[1]"
    MY_PROFILE = "//h1[contains(text(),'My Profile')]"
    EDIT_PROFILE = "//span[text()='Edit']"
    FIRST_NAME = "//input[@id='first-name']"
    LAST_NAME = "//input[@id='last-name']"
    SELECT_COUNTRY = "//span[text()='India']"
    SELECT_CITY = "//span[text()='Bangalore, Bangalore, Karnataka, India']"
    WHATSAPP_NUMBER = "//input[@id='mobile-number']"
    VERIFY_WHATSAPP_NUMBER = "//p[text()='Verify']"
    UPDATE_PROFILE = "//span[text()='Update']"
    LOGOUT_BUTTON = "//h1[normalize-space()='Logout']"
>>>>>>> Stashed changes
