
class LoginLocators:
    GET_STARTED_BUTTON = "//button[contains(@class,'guest-started-button')]"
    LOGIN_BUTTON = "//p[text()='Continue with Email']"
    USERNAME = "//input[@name='email']"
    NEXT_BUTTON = "//button[text()='Next']"
    PASSWORD = "//input[@placeholder='Enter password']"
    SUBMIT_BUTTON = "//button[text()='Submit']"
    WADHWANI_LOGO = "//img[@alt='wadhwani logo white color']"
    HOME_BUTTON = "//div[@id='Home']"
    CHAT_ICON = "//p[contains(text(),'Messages & Discussions')]"
    NOTIFICATIONS_ICON = "(//div[contains(@class,'chat_container')]//img)[4]"
    CLOSE_NOTIFICATION = "//img[contains(@class,'notification__title__cross')]"
    PROFILE_ICON = "(//div[@class='profile_container_wrapper'])"
    MY_PROFILE = "//h1[contains(text(),'My Profile')]"
    EDIT_PROFILE = "//button[text()='Edit']"
    EDIT_BUTTON = "//button[@class='ant-btn ant-btn-default edit-button']"
    FIRST_NAME = "//input[@id='first-name']"
    UPDATE_BUTTON = "//button[contains(@class,'update-button') or .//span[normalize-space()='Update'] or normalize-space()='Update']"
    ACCOUNTS_MENU="//button[@aria-label='Accounts menu']//img"
