class PlacementPrepLocators:
    PLACEMENT_PREP="//div[@id='Placement']"
    PPR_EXPLORE_BUTTON="//span[text()='Personal Pitch Trainer']/parent::div//span[text()='Explore']"
    LANGUAGE_DROPDOWN="//p[text()='English']"
    CREATE_PITCH_BUTTON="//span[text()='Create Your Pitch']"
    POPUP_HEADSUP="//span[text()='Yes, Continue']"
    ###########################################################################################################
    CB_EXPLORE_BUTTON="//span[text()='Career Buddy']/parent::div//span[text()='Explore']"
    CB_START_BUTTON="//span[text()='Start']"
    LANGUAGE_SELECTION="//span[text()='Select Language']"
    ENGLISH_OPTION="//div[text()='English']"
    INTRESTED_SECTOR_OPTION="//div[text()='Healthcare']"
    Next_BUTTON="//span[text()='Next']"
    BOOKSESSION_BUTTON="//span[text()='Book Session']"
    DATE_PICKER_CELL="//td[@class='ant-picker-cell ant-picker-cell-in-view']"
    SLOT_SELECTION_BUTTON="//div[@class='cal-container-right']//button[1]"
    PURPOSE_OF_SESSION="//span[text()='Job Search Strategy']"
    INTERVIEW_PREPARATION_OPTION="//span[text()='Interview Preparation']"
    SPECIFIC_OUTCOME_TEXTAREA="//label[contains(text(),'What specific')]/following::textarea"
    #send some eg text "I need help identifying the right career path based on my background."
    UPLOAD_RESUME_BUTTON="//div[@class='upload_resume_btn']"
    CHECKBOX="//input[@type='checkbox']"
    BOOK_BUTTON="//span[text()='Book']"
    VALIDATE_COPYLINK="//span[text()='Copy Link']"
