class PlacementLocators:
    PLACEMENT_PREP_MENU = "//div[@id='Placement']"
    PERSONAL_PITCH_TILE = "//span[contains(text(), 'Personal Pitch Trainer')]"
    EXPLORE_BTN = "//span[contains(text(), 'Personal Pitch Trainer')]/ancestor::div[contains(@class, 'placement_prep_landing_page_card')]//button[contains(@class, 'explore_btn')]"
    PERSONAL_PITCH_HEADER = "//h4[contains(text(), 'Personal Pitch')]"
    CREATE_PITCH_BTN = "//button[contains(@class, 'create-your-pitch-button')]"
    RESUME_PITCH_MODAL = "//div[@class='ant-modal-title' and text()='Resume Your Pitch']"
    START_NEW_PITCH_BTN = "//button[contains(@class, 'discard-button')]//span[text()='Start New Pitch']"
    STEP_1_INDICATOR = "//span[@class='ant-steps-icon' and @data-label='1']"
    TARGET_JOB_HEADER = "//h1[contains(@class, 'job-role-heading')]"
    JOB_ROLE_INPUT = "//input[@id='job-role-input']"
    JOB_ROLE_CONTAINER = "//div[contains(@class, 'wf_animated_input')]"
    JOB_ROLE_SUBMIT_BTN = "//div[contains(@class, 'validate-job-role-correct')]"
    UNDERSTAND_BTN = "//button[contains(@class, 'understand-button')]"
    STEP_2_INDICATOR = "//span[@class='ant-steps-icon' and @data-label='2']"
    RECORD_PITCH_HEADER = "//h4[contains(@class, 'record-pitch-heading')]"
    RECORD_BTN = "//p[contains(@class, 'record-button') and text()='Record']"
    LEAVING_PITCH_MODAL = "//div[@class='ant-modal-title' and contains(text(), 'Leaving Pitch Creation')]"
    SAVE_EXIT_BTN = "//button[contains(@class, 'discard-button')]//span[text()='Save & Exit']"
    LANGUAGE_ALERT_HEADER = "//span[contains(text(), 'Heads up!')]"
