class SettingsZoomConnectLocators:
    PROFILE_ICON ="(//div[@class='ml-3 profile_container'])[1]"
    SETTINGS_ICON="(//div[@class='app__layout_menu_item'])[3]"
    ACCOUNTS_MENU="(//div[@class='ant-row userSettings_menuItem userSettings_menuItem_selected css-1v613y0'])[1]"
    MEETING_CARD="(//div[@class='section-container'])[1]"
    ZOOM_SETTINGS_ARROW="(//img[@alt='right_arrow'])[1]"
    DELINKED_POPUP="(//div[@class='ant-notification-notice alert-notification ant-notification-notice-closable'])[1]"
    DELINKED_CLOSEICON="//span[@aria-label='close']//*[name()='svg']"
    SIGNIN_WITH_ZOOM_SECTION="(//div[@class='ant-row zoomSync_container css-1v613y0'])[1]"
    ZOOMCONNECTION_TOGGLER="//span[@class='ant-switch-inner']"
    MEETINGS_CARD="(//div[@class='ant-row zoom-container css-1v613y0'])[1]"
    SIGNIN_BUTTON="(//button[@class='ant-btn css-1v613y0 ant-btn-default ant-btn-color-default ant-btn-variant-outlined ant-btn-block primary_button zoom-button'])[1]"
    ZOOM_EMAIL_INPUT="(//input[@id='email'])[1]"
    ZOOM_PASSWORD_INPUT="(//input[@id='password'])[1]"
    ZOOM_SIGNIN_BUTTON="(//button[@id='js_btn_login'])[1]"
    BACK_ARROW="(//img[@class='wf_image left_icon no-js-arrow-left-dark'])[1]"
    MEETINGS_DISCONNECT_CONTAINER="(//div[@class='ant-row zoom-container css-1v613y0'])[1]"
    MEETINGS_DISCONNECT_BUTTON="(//button[@class='ant-btn css-1v613y0 ant-btn-default ant-btn-color-default ant-btn-variant-outlined ant-btn-block primary_button zoom-button'])[1]"
    