class CommonCreateMeetingLocators:
#UPCOMING ACTIVITIES
    UPCOMING_ACTIVITIES_SECTION="//P[contains(text(),'Upcoming Activities')]"
    CREATE_MEETING_BUTTON="//P[contains(text(),'Create Meeting')]"
    MEETING_TITLE="//div[contains(text(),'Meeting')]"
    MEETING_CLOSE_ICON="(//*[name()='svg'][@class='lucide lucide-x'])[1]"
    CREATE_NEW_MEETING_CARD="(//label[@class='ant-radio-wrapper ant-radio-wrapper-checked'])[1]"
    MEETING_TITLE_INPUT="(//div[@class='wf_animated_input meeting_title'])[1]"
    SELECT_DATE_INPUT="(//div[@type='button'])[1]"
    CALENDAR_DATE_PICKER="(//div[@class='ant-picker-input'])[1]"
    CALENDAR_OK_BUTTON="(//button[normalize-space()='OK'])[1]"
    TIME_SLOT_DROPDOWN="(//div[@class='ant-select-selector'])[1]"
    MIN_SLOT="(//div[contains(@class,'ant-select-item-option-content') and text()='15 mins'])[1]"
    #ZOOM_MEETING_CHECKBOX="(//span[@class='ant-checkbox-inner'])[1]"
    MEETING_AGENDA_FIELD="(//div[@class='wf_animated_input meeting_agenda'])[1]"
    MEETING_AGENDA_INPUT="(//input[@id='agenda'])[1]"
    NOTES_INPUT="(//span[@class='ant-input-textarea'])[1]"
    CREATING_MEETING_BUTTON="(//button[normalize-space()='Create a Meeting'])[1]"
    MEETING_CONFIRMATION_CARD="(//div[@class='ant-modal-body'])[1]"
    MEETING_CONFIRMATION_OKAY_BUTTON="//button[contains(text(),'Okay')]"
    MEETING_CARD="(//div[@class='card-wrapper meeting-card-wrapper happening_meeting ongoing_meeting_card'])[1]"
    MEETING_NAME_IN_CARD="(//h5[normalize-space()='Automation Meeting'])[1]"
    MEET_CHECK_CARD="(//div[@class='section_card_container meeting-details-view-section'])[1]"
    NOTES_CARD="(//div[@class='section_card_container meeting-notes-container'])[1]"
    #UPDATE MEETING
    EDIT_MEETING_BUTTON="//img[@class='edit-pencil']"
    UPDATE_CHANGES_BUTTON="(//button[normalize-space()='Update Changes'])[1]"
    #DELETE MEETING
    DELETE_MEETING_BUTTON="(//img[@alt='delete-icon'])[1]"
    DELETE_CONFIRMATION_BUTTON="(//button[normalize-space()='Delete'])[1]"
    EVENT_DELETED_TOAST="(//div[@id='app-message-container'])[1]"
