class CommonBatchMembersLocators:
    FIRST_BATCH_CARD = "(//td[contains(@class,'batch-list-content-bold')])[1]"
    BATCH_NAME = "//div[@class='batch-name-div']"
    BATCH_MEMBERS_TAB = "(//p[normalize-space()='Batch Members'])[1]"
    BATCH_MEMBERS_HEADER_SECTION="(//section[contains(@class,'student-section-header-container')])[1]"
    MANAGE_STUDENTS_BUTTON="//span[contains(text(),'Manage Students')]"
    INVITE_STUDENTS_BUTTON="//button[normalize-space()='Invite Students']"
    INVITE_BATCHCODE="(//div[@class='batch-code'])[1]"
    BATCHCODE_COPY_BUTTON="(//img[@alt='copy-batch-code'])[1]"
    ENTER_STUDENT_EMAIL_INPUT="(//input[@placeholder='Enter Student Email'])[1]"
    ENTER_STUDENT_INVITE_BUTTON="(//button[contains(text(),'Send Invite')])[2]"
    DOWNLOAD_TEMPLATE_LINK="//a[contains(text(),'download template ')]"
    UPLOAD_FILE_BUTTON="//button[normalize-space()='Upload File']"
    UPLOAD_FILE_INVITE_BUTTON="(//button[contains(text(),'Send Invite')])[1]"
    UPLOAD_USERS_STATUS_BAR="//div[@class='ant-progress-inner']"
    UPLOAD_USERS_DOWNLOAD_BUTTON="(//button[normalize-space()='Download'])[1]"
    INVITE_STUDENTS_BACK_ARROW="(//img[@alt='Go back'])[1]"

    ##Active & Pending students tabs
    BATCH_STUDENTS_TAB="//div[contains(text(),'Batch Students')]"
    DOWNLOAD_CERTIFICATE_VIEW_BUTTON="//span[contains(text(),'View')]"
    CERTIFICATE_IMAGE="(//img[@alt='Certificate Preview'])[1]"
    VIEW_CERTIFICATE_DOWNLOAD_CERTIFICATE_BUTTON="//button[contains(text(),'Download Certificate')][1]"
    VIEW_CERTIFICATE_CLOSE_ICON="(//button[@class='custom-modal-close'])[1]"
    DOWNLOAD_CERTIFICATE_DOWNLOAD_BUTTON="//span[contains(text(),'Download')]"
    USER_DELETE_BUTTON="xpath=(//div[contains(@class,'remove-student')] | //img[@alt='delete'] | //img[contains(@class,'trash')])[1]"
    REMOVE_STUDENT_POPUP="//div[contains(@class,'ant-modal-wrap') and not(contains(@style,'display: none'))] | //div[contains(@class,'ant-modal-content')] | //div[contains(@class,'ant-modal')]"
    REMOVE_STUDENT_NO_BUTTON="//div[contains(@class,'ant-modal')]//button[normalize-space()='No'] | (//button[normalize-space()='No'])[1]"
    REMOVE_STUDENT_YES_BUTTON="//div[contains(@class,'ant-modal')]//button[normalize-space()='Yes'] | (//button[normalize-space()='Yes'])[1]"
    MANAGE_STUDENTS_BACK_ARROW="(//img[@alt='Go back'])[1]"
    PENDING_REQUESTS_TAB="//div[contains(text(),'Pending Requests')]"
    FIRST_USER_RESEND_BUTTON="(//span[contains(text(),'Resend Request')])[1]"
    RESEND_OTP_POPUP="(//div[@class='ant-modal-body'])[1]"
    RESEND_OTP_POPUP_YES_BUTTON="(//button[normalize-space()='Yes'])[1]"
    BATCH_MEMBERS_CARD="(//div[@class='section_card_container cohort-member-card-container'])[1]"
    FIRST_BATCH_MEMBERS_CHAT_BUTTON="(//h2[contains(normalize-space(),'Chat')] | //button[contains(normalize-space(),'Chat')] | //img[contains(translate(@alt,'CHAT','chat'),'chat')])[1]"
