class CommonSettingsZoomConnectLocators:
    PROFILE_ICON ="(//div[@class='ml-3 profile_container'])[1]"
    SETTINGS_ICON="//div[@id='Settings']"
    ACCOUNTS_MENU="(//h1[text()='Accounts'])"
    MEETING_CARD="(//div[@class='section-container'])[1]"
    ZOOM_SETTINGS_ARROW="//*[contains(translate(normalize-space(.), 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 'ZOOM') or contains(translate(normalize-space(.), 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 'MEETING')]/ancestor::div[contains(@class,'section-container') or contains(@class,'zoom-container') or contains(@class,'item')][1]//img[@alt='right_arrow' or contains(@alt,'arrow')]"
    DELINKED_POPUP="(//div[@class='ant-notification-notice alert-notification'])[1]"
    DELINKED_CLOSEICON="//span[@class='ant-notification-notice-close-x']//*[name()='svg']"
    SIGNIN_WITH_ZOOM_SECTION="(//div[@class='ant-row zoomSync_container'])[1]"
    ZOOMCONNECTION_TOGGLER="//button[contains(@class,'wf_switch') and contains(@class,'toggle_button')]"
    MEETINGS_CARD="(//div[@class='zoom-container'])[1]"
    SIGNIN_BUTTON="(//button[text()='Sign In'])[1]"
    ZOOM_EMAIL_INPUT="(//input[@id='email'])[1]"
    ZOOM_PASSWORD_INPUT="(//input[@id='password'])[1]"
    ZOOM_SIGNIN_BUTTON="(//button[@id='js_btn_login'])[1]"
    BACK_ARROW="(//img[contains(@class,'left_icon') or contains(@alt,'left') or contains(@alt,'back') or contains(@alt,'arrow')])[1]"
