class CommonActivityInsightsLocators:
    FIRST_BATCH_CARD = "(//td[@class='ant-table-cell batch-list-content-bold'])[1]"
    BATCH_NAME = "//div[@class='batch-name-div']"
    ACTIVITY_INSIGHTS_TAB="(//p[normalize-space()='Activity Insights'])[1]"
    SUBMISSION_INSIGHTS_HEADER_SECTION="(//div[@class='collaborate-insights-header'])[1]"
    MODULE_COLUMN_TITLE="(//div[normalize-space()='Module'])[1]"
    LESSON_NAME_COLUMN_TITLE="(//div[normalize-space()='Lesson Name'])[1]"
    STUDENTS_SUBMITTED_I_ICON="(//img[@alt='Info'])[1]"
    STUDENTS_SCORED_I_ICON="(//img[@alt='Info'])[2]"
    PITCH_TRAINER_PREVIDEO_ARROW_ICON="(//img[@alt='Back'])[1]"
    ACTIVE_LISTENING_ARROW_ICON="(//img[@alt='Back'])[2]"
    LA_AND_TA_ARROW_ICON="(//img[@alt='Back'])[3]"
    PITCH_TRAINER_POSTVIDEO_ARROW_ICON="(//img[@alt='Back'])[4]"
    HEADING_SECTION="(//div[@class='heading-section'])[1]"
    INSIGHTS_TABLE="(//div[@class='lesson-insignts-table'])[1]"
    BACK_ARROW="(//img[@class='wf_image back-button no-js-insight-back-button'])[1]"
